Remove HiLink commands
xuhdev/syntax-dosini.vim pull request #4
Opened 2018-09-10 23:42 UTC by ix5

Do as vim/vim and neovim/neovim do since vim/vim@f37506f60f and neovim/neovim@86b596dc7a
Depends on #3

2018-09-11 02:06 UTC, xuhdev commented
Thanks! Can you rebase?

2018-09-11 02:22 UTC, ix5 commented
Rebased, that should do it.

2018-09-11 03:06 UTC, xuhdev requested changes
Everything looks good, except for that in the first commit, can you explicitly state in the log that the support of older versions of Vim have been dropped? I'm unsure which version it is (the version in which Vim switched to "hi def link"). After this, I will merge your PR. Thanks a lot!

2018-09-11 03:15 UTC, ix5 commented
As far as I can tell, vim removed the `HiLink` shim in v7.4.2297 for all runtime files, but `hi def link` is supported since 5.8

2018-09-11 03:23 UTC, xuhdev commented on syntax/dosini.vim
> +if exists("b:current_syntax")
At least this change has removed support for 5.x.

2018-09-11 03:23 UTC, xuhdev commented on syntax/dosini.vim
> -  if version < 508
So does this

2018-09-11 16:20 UTC, ix5 commented
I've updated the commit

2018-09-11 19:03 UTC, xuhdev approved these changes

2018-09-11 19:03 UTC, merged

2018-09-11 19:03 UTC, xuhdev commented
Cool, thanks!

2018-09-12 19:01 UTC, ix5 commented
Nice, thanks for merging. Can you keep me informed when the patch gets merged into vim, so I can ping the neovim folks?

2018-09-12 19:06 UTC, xuhdev commented
@ix5 All runtime files in Vim are updated periodically: There is usually no special treatment of any single runtime files and I will not be notified. If you always use the latest version, you'll see that when someday you run `git pull` and find runtime files updated.

2018-09-12 19:08 UTC, ix5 commented
Alright, thanks!